esphome:
  name: my-panasonic-ac
  friendly_name: My Panasonic AC

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:
  level: VERY_VERBOSE
  logs:
    api.service: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret my_panasonic_ac_api_encryption_key

ota:
  - platform: esphome
    password: !secret my_panasonic_ac_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

#############################
## Panasonic AC controller ##
#############################
uart:
  rx_pin: GPIO18
  tx_pin: GPIO19
  baud_rate: 9600
  parity: EVEN
  stop_bits: 1

external_components:
  source:
    type: local
    path: components
  components: [panasonic_ac]

climate:
  - platform: panasonic_ac
    name: None
    traits:
      vertical_swing_mode:
        supported: true
        selector:
          name: Vertical Swing Mode
      horizontal_swing_mode:
        supported: false
      nanoex_mode:
        supported: true
        switch:
          name: NanoeX
      outside_temperature:
        supported: false
      current_power_consumption:
        supported: true
        sensor:
          name: Power Consumption
