esphome:
  name: my-panasonic-ac
  friendly_name: My Panasonic AC

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:
  level: VERY_VERBOSE
  logs:
    api.service: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret my_panasonic_ac_api_encryption_key

ota:
  - platform: esphome
    password: !secret my_panasonic_ac_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

#############################
## Panasonic AC controller ##
#############################
uart:
  rx_pin: GPIO18
  tx_pin: GPIO19
  baud_rate: 9600
  parity: EVEN
  stop_bits: 1

external_components:
  source:
    type: local
    path: components
  components: [panasonic_ac]

climate:
  - platform: panasonic_ac
    name: None
    icon: mdi:air-conditioner
    horizontal_swing_select:
      name: Horizontal Swing Mode
    vertical_swing_select:
      name: Vertical Swing Mode
    nanoex_switch:
      name: NanoeX Switch
    outside_temperature:
      name: Outside Temperature
    current_power_consumption:
      name: AC Power Consumption

    # Other options:
    # eco_switch:
    #  name: Livingroom Panasonic AC Eco Switch
    # mild_dry_switch:
    #   name: Panasonic AC Mild Dry Switch
    # Useful when the ac does not report a current temperature (CZ-TACG1 only)
    # current_temperature_sensor: temperature_sensor_id
